version: '2'

services:
  mongodb:
    image: 'mmakertrade/mongodb:4.0-rc'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/mmakertrade'

volumes:
  redis_data:
    driver: local